### ISSUE TITLE
Using fetch makes this incompatible with Node

### ISSUE THREAD

**Issue by christopher-caldwell** [asbeane/mlb-stats-api#18]
By using the browser's fetch, you take away compatibility with Node unless you use a [patch](https://github.com/node-fetch/node-fetch#providing-global-access) or some sort of polyfill.

It seems you intentionally went away from axios, does this mean end users have to use the tools above for this to work?

**Comment by alittletf** [comment]
Just wanted to +1 the above. I tried to access this using Node and got: 

```
        return fetch(`${this.host}v1/game/${gamePk}`, { params: params });
        ^

ReferenceError: fetch is not defined
```
Would love to use this package!

**Comment by Iliannnn** [comment]
This does not take away combability with Node, you are just using an older version of Node. Make sure you have `v17.5` or higher, LTS is fine.

**Comment by christopher-caldwell** [comment]
Hmm. If that's the case, then there should be an `engines` key in the `package.json`.

**Comment by Iliannnn** [comment]
Will add it
