### ISSUE TITLE
getGame() gives error

### ISSUE THREAD

**Issue by bradmallett** [asbeane/mlb-stats-api#20]
When calling getGame like this:
```js
const res = await mlbStats.getGame({ pathParams: { gamePk: 717754 }});
const game = await res.json()
```
I'm getting this error:
```js
{
  messageNumber: 14,
  message: "Request method 'GET' not supported",
  timestamp: '2023-06-16T21:37:06.585597829Z',
  traceId: null
}
```
Am I missing something? I'm trying to follow your readme

**Comment by Iliannnn** [comment]
The function you're using seems to be pointing to the wrong endpoint, `/game/{gamePk}`, which doesn't exist. It looks like you want to fetch data from the live feed endpoint, `/game/{gamePk}/feed/live`, instead. To do this, you should use the `getGameFeed()` function.

I noticed a mistake in the README where it says you can get the live feed using the `getGame()` function, but that's not correct. I'll fix this and open a pull request to update the README and remove the incorrect function.

**Comment by bradmallett** [comment]
Ok, so for example if I wanted only the teams with the league id of 103, I would think I would do this: 
getTeams({params: { leagueId: 103 } });
Doesn't seem to work. I'm learning, you can probably tell, but am I doing this correctly?

**Comment by Iliannnn** [comment]
Use the `leagueIds` parameter:
```js
getTeams({ params: { leagueIds: 103 } });
```

For additional information, access a minimal version of the private documentation by using the JSON from [here](https://www.reddit.com/r/mlbdata/comments/ngc8b3/mlb_statsapi_swaggerjson/) in [SwaggerEditor](https://editor-next.swagger.io/). Let me know if you have more questions.
