### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StewieHF** [asbeane/mlb-stats-api#23]
Hi, i have a real problem actually knowing what the parameters are for each endpoint, the MLB will not allow me access to their API directly and thus i cannot see any documentation around this, i don't suppose you might have some sort of documentation?

**Comment by Iliannnn** [comment]
This wrapper doesn't really have a comprehensive documentation, no. But there is a very helpful documentation for the [MLB-StatsAPI Python wrapper](https://pypi.org/project/MLB-StatsAPI/) that contains all endpoints and parameters here: https://github.com/toddrob99/MLB-StatsAPI/wiki/Endpoints

If you have more questions, feel free to ask in [r/mlbdata](https://www.reddit.com/r/mlbdata/) on Reddit.

**Comment by StewieHF** [comment]
Thank you very much, i had found that literally the day i sent this message and started looking through it, so thanks for confirming its a good source too :)

**Comment by Iliannnn** [comment]
Could you close this @StewieHF ?
